// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://wlcjihfpfxpjfnbrvwcp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndsY2ppaGZwZnhwamZuYnJ2d2NwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzM5NDY3OTEsImV4cCI6MjA4OTUyMjc5MX0.z_ihMQB0xbJX3nqXitA0GNAw5ZSMkY1qSTTd3nuAW9M";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);